// Code generated by protoc-gen-go.
// source: beans.useroptmessage.proto
// DO NOT EDIT!

/*
Package beans is a generated protocol buffer package.

It is generated from these files:
	beans.useroptmessage.proto

It has these top-level messages:
	UesrOptionMessage
*/
package beans

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type UesrOptionMessage struct {
	UserOpt          *int32 `protobuf:"varint,1,opt,name=userOpt" json:"userOpt,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UesrOptionMessage) Reset()                    { *m = UesrOptionMessage{} }
func (m *UesrOptionMessage) String() string            { return proto.CompactTextString(m) }
func (*UesrOptionMessage) ProtoMessage()               {}
func (*UesrOptionMessage) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *UesrOptionMessage) GetUserOpt() int32 {
	if m != nil && m.UserOpt != nil {
		return *m.UserOpt
	}
	return 0
}

func init() {
	proto.RegisterType((*UesrOptionMessage)(nil), "beans.UesrOptionMessage")
}

var fileDescriptor2 = []byte{
	// 87 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x4a, 0x4a, 0x4d, 0xcc,
	0x2b, 0xd6, 0x2b, 0x2d, 0x4e, 0x2d, 0xca, 0x2f, 0x28, 0xc9, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0xcb, 0x29, 0xa9, 0x70, 0x09, 0x86, 0xa6,
	0x16, 0x17, 0xf9, 0x17, 0x94, 0x64, 0xe6, 0xe7, 0xf9, 0x42, 0x54, 0x08, 0xf1, 0x73, 0xb1, 0x83,
	0xf4, 0x00, 0x05, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xac,
	0xf9, 0x23, 0x4b, 0x49, 0x00, 0x00, 0x00,
}
