// Code generated by protoc-gen-go.
// source: beans.devmessage.proto
// DO NOT EDIT!

/*
Package beans is a generated protocol buffer package.

It is generated from these files:
	beans.devmessage.proto

It has these top-level messages:
	DevMessage
*/
package beans

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type DevMessage struct {
	AngleAlpha       *float32 `protobuf:"fixed32,1,opt,name=angle_alpha,def=0" json:"angle_alpha,omitempty"`
	AngleBeta        *float32 `protobuf:"fixed32,2,opt,name=angle_beta,def=0" json:"angle_beta,omitempty"`
	AngleGamma       *float32 `protobuf:"fixed32,3,opt,name=angle_gamma,def=0" json:"angle_gamma,omitempty"`
	AcceX            *float32 `protobuf:"fixed32,4,opt,name=acce_x,def=0" json:"acce_x,omitempty"`
	AcceY            *float32 `protobuf:"fixed32,5,opt,name=acce_y,def=0" json:"acce_y,omitempty"`
	AcceZ            *float32 `protobuf:"fixed32,6,opt,name=acce_z,def=0" json:"acce_z,omitempty"`
	AcceAlpha        *float32 `protobuf:"fixed32,7,opt,name=acce_alpha,def=0" json:"acce_alpha,omitempty"`
	AcceBeta         *float32 `protobuf:"fixed32,8,opt,name=acce_beta,def=0" json:"acce_beta,omitempty"`
	AcceGamma        *float32 `protobuf:"fixed32,9,opt,name=acce_gamma,def=0" json:"acce_gamma,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DevMessage) Reset()                    { *m = DevMessage{} }
func (m *DevMessage) String() string            { return proto.CompactTextString(m) }
func (*DevMessage) ProtoMessage()               {}
func (*DevMessage) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

const Default_DevMessage_AngleAlpha float32 = 0
const Default_DevMessage_AngleBeta float32 = 0
const Default_DevMessage_AngleGamma float32 = 0
const Default_DevMessage_AcceX float32 = 0
const Default_DevMessage_AcceY float32 = 0
const Default_DevMessage_AcceZ float32 = 0
const Default_DevMessage_AcceAlpha float32 = 0
const Default_DevMessage_AcceBeta float32 = 0
const Default_DevMessage_AcceGamma float32 = 0

func (m *DevMessage) GetAngleAlpha() float32 {
	if m != nil && m.AngleAlpha != nil {
		return *m.AngleAlpha
	}
	return Default_DevMessage_AngleAlpha
}

func (m *DevMessage) GetAngleBeta() float32 {
	if m != nil && m.AngleBeta != nil {
		return *m.AngleBeta
	}
	return Default_DevMessage_AngleBeta
}

func (m *DevMessage) GetAngleGamma() float32 {
	if m != nil && m.AngleGamma != nil {
		return *m.AngleGamma
	}
	return Default_DevMessage_AngleGamma
}

func (m *DevMessage) GetAcceX() float32 {
	if m != nil && m.AcceX != nil {
		return *m.AcceX
	}
	return Default_DevMessage_AcceX
}

func (m *DevMessage) GetAcceY() float32 {
	if m != nil && m.AcceY != nil {
		return *m.AcceY
	}
	return Default_DevMessage_AcceY
}

func (m *DevMessage) GetAcceZ() float32 {
	if m != nil && m.AcceZ != nil {
		return *m.AcceZ
	}
	return Default_DevMessage_AcceZ
}

func (m *DevMessage) GetAcceAlpha() float32 {
	if m != nil && m.AcceAlpha != nil {
		return *m.AcceAlpha
	}
	return Default_DevMessage_AcceAlpha
}

func (m *DevMessage) GetAcceBeta() float32 {
	if m != nil && m.AcceBeta != nil {
		return *m.AcceBeta
	}
	return Default_DevMessage_AcceBeta
}

func (m *DevMessage) GetAcceGamma() float32 {
	if m != nil && m.AcceGamma != nil {
		return *m.AcceGamma
	}
	return Default_DevMessage_AcceGamma
}

func init() {
	proto.RegisterType((*DevMessage)(nil), "beans.DevMessage")
}

var fileDescriptor5 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x4a, 0x4d, 0xcc,
	0x2b, 0xd6, 0x4b, 0x49, 0x2d, 0xcb, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x05, 0x8b, 0x2b, 0x5d, 0x60, 0xe4, 0xe2, 0x72, 0x49, 0x2d, 0xf3, 0x85,
	0xc8, 0x09, 0x89, 0x71, 0x71, 0x27, 0xe6, 0xa5, 0xe7, 0xa4, 0xc6, 0x27, 0xe6, 0x14, 0x64, 0x24,
	0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x59, 0x31, 0x1a, 0x08, 0x89, 0x72, 0x71, 0x41, 0xc4, 0x93,
	0x52, 0x4b, 0x12, 0x25, 0x98, 0x60, 0xc2, 0x70, 0xe5, 0xe9, 0x89, 0xb9, 0xb9, 0x89, 0x12, 0xcc,
	0x30, 0x71, 0x41, 0x2e, 0xb6, 0xc4, 0xe4, 0xe4, 0xd4, 0xf8, 0x0a, 0x09, 0x16, 0x74, 0xa1, 0x4a,
	0x09, 0x56, 0x74, 0xa1, 0x2a, 0x09, 0x36, 0x64, 0x7b, 0x40, 0x42, 0x10, 0xeb, 0xd9, 0x61, 0xc2,
	0x22, 0x5c, 0x9c, 0x60, 0x61, 0xb0, 0xed, 0x1c, 0xe8, 0x8a, 0x21, 0x96, 0x73, 0x42, 0x85, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x41, 0x26, 0x6d, 0xdc, 0xf2, 0x00, 0x00, 0x00,
}
